stages:
  - build

build:
  stage: build
  image: sacurio/debianpackager:0.2
  before_script:
    - 'apt-get update && apt-get install -y --no-install-recommends libglib2.0-dev libcairo2-dev libpango1.0-dev libgtk-3-dev libgio-cil xvfb xauth'
  script:
    - gbp buildpackage --git-ignore-branch
    - mkdir debian_build
    - 'cp ../*.{deb,dsc,changes,tar.xz} debian_build'
  artifacts:
    paths:
      - 'debian_build/*.deb'
      - 'debian_build/*.dsc'
      - 'debian_build/*.changes'
      - 'debian_build/*.tar.xz'