name: Build and test on MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install gtk
      run: brew install gobject-introspection gtk+3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
